server:
  #   port: 8083
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cetdemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    #    password:
    password: Cet123456
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: cet@nies.org
    password: Njs123456
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# windows
file:
  path:
    #      E://CET//
    /usr/local/cet/
# docker run  -v /root/Cet/prove:/usr/local/cet  --net=host  --name=cetserver  -d -p 8081:8081 cetserver